import React,{useEffect,useRef,useState} from 'react';
import './index.css';
const K1='fabric_rp341_state',K2='fabric_rp341_room';
export default function App(){
 const [messages,setMessages]=useState([]),[status,setStatus]=useState('Starting Fabric…'),[input,setInput]=useState(''),[busy,setBusy]=useState(true),[live,setLive]=useState(null);const end=useRef(null);
 const add=(role,text,meta='')=>setMessages(x=>[...x,{role,text,meta}]);
 const init=async(force=false)=>{setBusy(true);setStatus('Starting Fabric…');try{if(force){localStorage.removeItem(K1);localStorage.removeItem(K2)}let s=localStorage.getItem(K1),r=localStorage.getItem(K2);if(!s||!r){const res=await fetch('/api/fabric',{cache:'no-store'}),d=await res.json();if(!res.ok)throw new Error(d.message||'Could not start Fabric');localStorage.setItem(K1,d.state_token);localStorage.setItem(K2,d.room_token)}setStatus('Fabric ready · RP341');return true}catch(e){setStatus('Startup error');add('fabric',e.message);return false}finally{setBusy(false)}};
 useEffect(()=>{init().then(ok=>{if(ok)add('fabric','Fabric is ready. Say something.')})},[]);useEffect(()=>end.current?.scrollIntoView({behavior:'smooth'}),[messages]);
 const talk=async()=>{const text=input.trim();if(!text||busy)return;setInput('');add('you',text);setBusy(true);setStatus('Fabric is processing…');try{const res=await fetch('/api/fabric',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,state_token:localStorage.getItem(K1),room_token:localStorage.getItem(K2)})});const d=await res.json();if(!res.ok)throw new Error(d.message||'Fabric request failed');localStorage.setItem(K1,d.state_token);localStorage.setItem(K2,d.room_token);setLive(d.live_state||null);add('fabric',d.reply||'(no verbal reply)',`Fabric · ${d.child_id||''} · clock ${d.clock_after??''}`);setStatus('Fabric ready · RP341')}catch(e){add('fabric','Interaction error: '+e.message);setStatus('Fabric error')}finally{setBusy(false)}};
 const reset=async()=>{if(!window.confirm('Reset this browser session to RP341?'))return;setMessages([]);setLive(null);const ok=await init(true);if(ok)add('fabric','Session reset to RP341.')};
 return <main><header><div className="eyebrow">Experimental interaction surface</div><h1>Talk to Fabric</h1><p>Qualified baseline: RP341 / v1.32.10. This is the real Fabric Learning Room response path, not ChatGPT speaking for it. Segment 2 and the full cognitive loop are still under construction.</p><div className="status"><span className="dot"/><span>{status}</span><button className="reset" onClick={reset}>Reset</button></div></header><section className="chat">{messages.map((m,i)=><React.Fragment key={i}><div className={'msg '+m.role}>{m.text}</div>{m.meta&&<div className="meta">{m.meta}</div>}</React.Fragment>)}<div ref={end}/></section><details><summary>Live cognitive state</summary><pre>{live?JSON.stringify(live,null,2):'No turn yet.'}</pre><div className="small">Session state is stored in this browser. Reset returns to the qualified RP341 baseline.</div></details><form onSubmit={e=>{e.preventDefault();talk()}}><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();talk()}}} disabled={busy} placeholder="Say something to Fabric…"/><button disabled={busy||!input.trim()}>Send</button></form></main>
}
